services:
  viale-manager-db:
    container_name: viale_manager_db
    image: postgres:14
    volumes:
      - viale-manager_db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: viale_manager
      POSTGRES_USER: viale
      POSTGRES_PASSWORD: password
    ports:
      - 54752:5432

volumes:
  viale-manager_db:
